# Ansible inventory generated by Terraform
%{ for name, data in vm_ips ~}
${name} ansible_host=${data.ip} ansible_user=ubuntu group=${data.group}
%{ endfor ~}

[scenario1]
%{ for name, data in vm_ips ~}%{ if data.group == "scenario1" }${name}
%{ endif }%{ endfor }

[scenario2]
%{ for name, data in vm_ips ~}%{ if data.group == "scenario2" }${name}
%{ endif }%{ endfor }

[scenario3]
%{ for name, data in vm_ips ~}%{ if data.group == "scenario3" }${name}
%{ endif }%{ endfor }

[scenario4]
%{ for name, data in vm_ips ~}%{ if data.group == "scenario4" }${name}
%{ endif }%{ endfor }

[all:vars]
ansible_ssh_private_key_file = ~/.ssh/p3-key.pem
ansible_python_interpreter = /usr/bin/python3
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q root@192.168.122.55 -o StrictHostKeyChecking=no" -o StrictHostKeyChecking=no'
